[package]
name = "rustmqttserverdemo"
version = "0.1.0"
edition = "2024"

[dependencies]
rumqttd = "0.19"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
log = "0.4"
env_logger = "0.11"
