# MQTT Broker 配置文件
id = 0

[router]
max_segment_size = 104857600
max_segment_count = 10
max_connections = 10000
max_outgoing_packet_count = 200

# TCP 监听器 - MQTT 3.1.1
[v4.1]
name = "tcp-v4"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1
    
[v4.1.connections]
connection_timeout_ms = 60000
max_client_id_len = 256
max_connections = 10000
max_payload_size = 268435455
max_inflight_count = 100
throttle_delay_ms = 0

# TCP 监听器 - MQTT 5.0
[v5.1]
name = "tcp-v5"
listen = "0.0.0.0:1884"
next_connection_delay_ms = 1

[v5.1.connections]
connection_timeout_ms = 60000
max_client_id_len = 256
max_connections = 10000
max_payload_size = 268435455
max_inflight_count = 100
throttle_delay_ms = 0

# WebSocket 监听器 (MQTT 3.1.1)
[ws.1]
name = "ws-v4"
listen = "0.0.0.0:8080"
next_connection_delay_ms = 1

[ws.1.connections]
connection_timeout_ms = 60000
max_client_id_len = 256
max_connections = 10000
max_payload_size = 268435455
max_inflight_count = 100
throttle_delay_ms = 0

# 控制台配置 (用于监控和管理)
[console]
listen = "0.0.0.0:3030"
